version: '3.9'

services:
  app:
    build: .
    volumes:
      - ${PWD}:/app
    ports:
      - 8080:8000
    networks:
      - internal
    depends_on:
      - mongo
      - redis

  consumer:
    build: .
    entrypoint: ["watchexec", "-r", "-e", "py", "--", "python", "invisible/consumers"]
    volumes:
      - ${PWD}:/app
    networks:
      - internal
    depends_on:
      - mongo
      - redis
      - kafka

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - internal

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8081:8081
    networks:
      - internal


  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=invisible
    networks:
      - internal

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - internal
    ports:
      - 8082:8081
    depends_on:
      - mongo

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 22181:2181
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 29092:29092
    networks:
      - internal
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    ports:
      - 8083:9000
    depends_on:
      - kafka
    networks:
      - internal

networks:
  internal:
    driver: bridge
