version: '3.9'

services:
  app:
    build: .
    volumes:
      - ${PWD}:/app
    ports:
      - 8080:8000
    networks:
      - internal

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - internal

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8081:8081
    networks:
      - internal


  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=invisible
    networks:
      - internal

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - internal
    ports:
      - 8082:8081
    depends_on:
      - mongo

networks:
  internal:
    driver: bridge
